### ISSUE TITLE
What about the FLOPs

### ISSUE THREAD

**Issue by yechaowang** [mogvision/pattern-net#2]
I notice that pattern-net has only 339k para. It's great but the cd layer and sr layer may occupy some computing resources.
I want to know the FLOPs of your model and how fast it works. Thanks a lot!

**Comment by mogvision** [comment]
Hi and many thanks for your query. The running time is 6.3 ms and 756M FLOPs/sample and  still we are interested in reducing the complexity by making the network more smart. Thanks, best wishes
